GET http://localhost:8080/api/locations/
Accept: application/json

###

POST http://localhost:8080/api/locations/
Content-Type: application/json

{
  "name": "Nem-Xuzhou",
  "lat": 16.12,
  "lon": 18.23
}

###
GET http://localhost:8080/api/locations?prefix=Nem-Xuzhou
Accept: application/json

###
PUT http://localhost:8080/api/locations/1
Content-Type: application/json

{
  "name":"Abalala",
  "lat": 0,
  "lon": 0
}

###
DELETE http://localhost:8080/api/locations/1

### validation

POST http://localhost:8080/api/locations/
Content-Type: application/json

{
  "name": "nnnnnn",
  "lat": -90,
  "lon": -9
}

###
PUT http://localhost:8080/api/locations/1
Content-Type: application/json

{
  "name":"Abalala",
  "lat": "",
  "lon": -10000
}